##**Fake News Classifier Using LSTM**
Dataset: https://www.kaggle.com/c/fake-news/data#

In [1]:
import pandas as pd

In [2]:
news=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train.txt', on_bad_lines='skip', engine='python')
news.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [3]:
news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20822 entries, 0 to 20821
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      20822 non-null  object
 1   title   20257 non-null  object
 2   author  18847 non-null  object
 3   text    20763 non-null  object
 4   label   20800 non-null  object
dtypes: object(5)
memory usage: 813.5+ KB

In [4]:
news.isnull().sum()

id           0
title      565
author    1975
text        59
label       22
dtype: int64

In [5]:
###Drop Nan Values
news=news.dropna()

In [6]:
# Keep only rows where label is '0' or '1'
news = news[news['label'].isin(['0', '1'])]

# Now convert label to integer
y = news['label'].astype(int)

In [7]:
## Get the Independent Features

X=news.drop('label',axis=1)

In [8]:
print(news['label'].unique())

['1' '0']

In [9]:
## Get the Dependent features
y = news['label'].astype('int')  # or use 'float' if needed

In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18283 entries, 0 to 20821
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      18283 non-null  object
 1   title   18283 non-null  object
 2   author  18283 non-null  object
 3   text    18283 non-null  object
dtypes: object(4)
memory usage: 714.2+ KB

In [11]:
y.info()

<class 'pandas.core.series.Series'>
Index: 18283 entries, 0 to 20821
Series name: label
Non-Null Count  Dtype
--------------  -----
18283 non-null  int64
dtypes: int64(1)
memory usage: 285.7 KB

In [12]:
X.shape

(18283, 4)

In [13]:
y.shape

(18283,)

In [14]:
import tensorflow as tf

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [16]:
### Vocabulary size
voc_size=5000

###**Onehot Representation**

In [17]:
messages=X.copy()

In [18]:
messages['title'][15]

'In Major League Soccer, Argentines Find a Home and Success - The New York Times'

In [19]:
messages.reset_index(inplace=True)

In [20]:
import nltk
import re
from nltk.corpus import stopwords

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [22]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])  # Regular Expression
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13283
13284
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
13443
13444
13445
13446
13447
13448
13449
13450
13451
13452
13453
13454
13455
13456
13457
13458
13459
13460
13461
13462
13463
13464
13465
13466
13467
13468
13469
13470
13471
13472
13473
13474
13475
13476
13477
13478
13479
13480
13481
13482
13483
13484
13485
13486
13487
13488
13489
13490
13491
13492
13493
13494
13495
13496
13497
13498
13499
13500
13501
13502
13503
13504
13505
13506
13507
13508
13509
13510
13511
13512
13513
13514
13515
13516
13517
13518
13519
13520
13521
13522
13523
13524
13525
13526
13527
13528
13529
13530
13531
13532
13533
13534
13535
13536
13537
13538
13539
13540
13541
13542
13543
13544
13545
13546
13547
13548
13549
13550
13551
13552
13553
13554
13555
13556
13557
13558
13559
13560
13561
13562
13563
13564
13565
13566
13567
13568
13569
13570
13571
13572
13573
13574
13575
13576
13577
13578
13579
13580
13581
13582
13583
13584
13585
13586
13587
13588
13589
13590
13591
13592
13593
13594
13595
13596
13597
13598
13599
13600
13601
13602
13603
13604
13605
13606
13607
13608
13609
13610
13611
13612
13613
13614
13615
13616
13617
13618
13619
13620
13621
13622
13623
13624
13625
13626
13627
13628
13629
13630
13631
13632
13633
13634
13635
13636
13637
13638
13639
13640
13641
13642
13643
13644
13645
13646
13647
13648
13649
13650
13651
13652
13653
13654
13655
13656
13657
13658
13659
13660
13661
13662
13663
13664
13665
13666
13667
13668
13669
13670
13671
13672
13673
13674
13675
13676
13677
13678
13679
13680
13681
13682
13683
13684
13685
13686
13687
13688
13689
13690
13691
13692
13693
13694
13695
13696
13697
13698
13699
13700
13701
13702
13703
13704
13705
13706
13707
13708
13709
13710
13711
13712
13713
13714
13715
13716
13717
13718
13719
13720
13721
13722
13723
13724
13725
13726
13727
13728
13729
13730
13731
13732
13733
13734
13735
13736
13737
13738
13739
13740
13741
13742
13743
13744
13745
13746
13747
13748
13749
13750
13751
13752
13753
13754
13755
13756
13757
13758
13759
13760
13761
13762
13763
13764
13765
13766
13767
13768
13769
13770
13771
13772
13773
13774
13775
13776
13777
13778
13779
13780
13781
13782
13783
13784
13785
13786
13787
13788
13789
13790
13791
13792
13793
13794
13795
13796
13797
13798
13799
13800
13801
13802
13803
13804
13805
13806
13807
13808
13809
13810
13811
13812
13813
13814
13815
13816
13817
13818
13819
13820
13821
13822
13823
13824
13825
13826
13827
13828
13829
13830
13831
13832
13833
13834
13835
13836
13837
13838
13839
13840
13841
13842
13843
13844
13845
13846
13847
13848
13849
13850
13851
13852
13853
13854
13855
13856
13857
13858
13859
13860
13861
13862
13863
13864
13865
13866
13867
13868
13869
13870
13871
13872
13873
13874
13875
13876
13877
13878
13879
13880
13881
13882
13883
13884
13885
13886
13887
13888
13889
13890
13891
13892
13893
13894
13895
13896
13897
13898
13899
13900
13901
13902
13903
13904
13905
13906
13907
13908
13909
13910
13911
13912
13913
13914
13915
13916
13917
13918
13919
13920
13921
13922
13923
13924
13925
13926
13927
13928
13929
13930
13931
13932
13933
13934
13935
13936
13937
13938
13939
13940
13941
13942
13943
13944
13945
13946
13947
13948
13949
13950
13951
13952
13953
13954
13955
13956
13957
13958
13959
13960
13961
13962
13963
13964
13965
13966
13967
13968
13969
13970
13971
13972
13973
13974
13975
13976
13977
13978
13979
13980
13981
13982
13983
13984
13985
13986
13987
13988
13989
13990
13991
13992
13993
13994
13995
13996
13997
13998
13999
14000
14001
14002
14003
14004
14005
14006
14007
14008
14009
14010
14011
14012
14013
14014
14015
14016
14017
14018
14019
14020
14021
14022
14023
14024
14025
14026
14027
14028
14029
14030
14031
14032
14033
14034
14035
14036
14037
14038
14039
14040
14041
14042
14043
14044
14045
14046
14047
14048
14049
14050
14051
14052
14053
14054
14055
14056
14057
14058
14059
14060
14061
14062
14063
14064
14065
14066
14067
14068
14069
14070
14071
14072
14073
14074
14075
14076
14077
14078
14079
14080
14081
14082
14083
14084
14085
14086
14087
14088
14089
14090
14091
14092
14093
14094
14095
14096
14097
14098
14099
14100
14101
14102
14103
14104
14105
14106
14107
14108
14109
14110
14111
14112
14113
14114
14115
14116
14117
14118
14119
14120
14121
14122
14123
14124
14125
14126
14127
14128
14129
14130
14131
14132
14133
14134
14135
14136
14137
14138
14139
14140
14141
14142
14143
14144
14145
14146
14147
14148
14149
14150
14151
14152
14153
14154
14155
14156
14157
14158
14159
14160
14161
14162
14163
14164
14165
14166
14167
14168
14169
14170
14171
14172
14173
14174
14175
14176
14177
14178
14179
14180
14181
14182
14183
14184
14185
14186
14187
14188
14189
14190
14191
14192
14193
14194
14195
14196
14197
14198
14199
14200
14201
14202
14203
14204
14205
14206
14207
14208
14209
14210
14211
14212
14213
14214
14215
14216
14217
14218
14219
14220
14221
14222
14223
14224
14225
14226
14227
14228
14229
14230
14231
14232
14233
14234
14235
14236
14237
14238
14239
14240
14241
14242
14243
14244
14245
14246
14247
14248
14249
14250
14251
14252
14253
14254
14255
14256
14257
14258
14259
14260
14261
14262
14263
14264
14265
14266
14267
14268
14269
14270
14271
14272
14273
14274
14275
14276
14277
14278
14279
14280
14281
14282
14283
14284
14285
14286
14287
14288
14289
14290
14291
14292
14293
14294
14295
14296
14297
14298
14299
14300
14301
14302
14303
14304
14305
14306
14307
14308
14309
14310
14311
14312
14313
14314
14315
14316
14317
14318
14319
14320
14321
14322
14323
14324
14325
14326
14327
14328
14329
14330
14331
14332
14333
14334
14335
14336
14337
14338
14339
14340
14341
14342
14343
14344
14345
14346
14347
14348
14349
14350
14351
14352
14353
14354
14355
14356
14357
14358
14359
14360
14361
14362
14363
14364
14365
14366
14367
14368
14369
14370
14371
14372
14373
14374
14375
14376
14377
14378
14379
14380
14381
14382
14383
14384
14385
14386
14387
14388
14389
14390
14391
14392
14393
14394
14395
14396
14397
14398
14399
14400
14401
14402
14403
14404
14405
14406
14407
14408
14409
14410
14411
14412
14413
14414
14415
14416
14417
14418
14419
14420
14421
14422
14423
14424
14425
14426
14427
14428
14429
14430
14431
14432
14433
14434
14435
14436
14437
14438
14439
14440
14441
14442
14443
14444
14445
14446
14447
14448
14449
14450
14451
14452
14453
14454
14455
14456
14457
14458
14459
14460
14461
14462
14463
14464
14465
14466
14467
14468
14469
14470
14471
14472
14473
14474
14475
14476
14477
14478
14479
14480
14481
14482
14483
14484
14485
14486
14487
14488
14489
14490
14491
14492
14493
14494
14495
14496
14497
14498
14499
14500
14501
14502
14503
14504
14505
14506
14507
14508
14509
14510
14511
14512
14513
14514
14515
14516
14517
14518
14519
14520
14521
14522
14523
14524
14525
14526
14527
14528
14529
14530
14531
14532
14533
14534
14535
14536
14537
14538
14539
14540
14541
14542
14543
14544
14545
14546
14547
14548
14549
14550
14551
14552
14553
14554
14555
14556
14557
14558
14559
14560
14561
14562
14563
14564
14565
14566
14567
14568
14569
14570
14571
14572
14573
14574
14575
14576
14577
14578
14579
14580
14581
14582
14583
14584
14585
14586
14587
14588
14589
14590
14591
14592
14593
14594
14595
14596
14597
14598
14599
14600
14601
14602
14603
14604
14605
14606
14607
14608
14609
14610
14611
14612
14613
14614
14615
14616
14617
14618
14619
14620
14621
14622
14623
14624
14625
14626
14627
14628
14629
14630
14631
14632
14633
14634
14635
14636
14637
14638
14639
14640
14641
14642
14643
14644
14645
14646
14647
14648
14649
14650
14651
14652
14653
14654
14655
14656
14657
14658
14659
14660
14661
14662
14663
14664
14665
14666
14667
14668
14669
14670
14671
14672
14673
14674
14675
14676
14677
14678
14679
14680
14681
14682
14683
14684
14685
14686
14687
14688
14689
14690
14691
14692
14693
14694
14695
14696
14697
14698
14699
14700
14701
14702
14703
14704
14705
14706
14707
14708
14709
14710
14711
14712
14713
14714
14715
14716
14717
14718
14719
14720
14721
14722
14723
14724
14725
14726
14727
14728
14729
14730
14731
14732
14733
14734
14735
14736
14737
14738
14739
14740
14741
14742
14743
14744
14745
14746
14747
14748
14749
14750
14751
14752
14753
14754
14755
14756
14757
14758
14759
14760
14761
14762
14763
14764
14765
14766
14767
14768
14769
14770
14771
14772
14773
14774
14775
14776
14777
14778
14779
14780
14781
14782
14783
14784
14785
14786
14787
14788
14789
14790
14791
14792
14793
14794
14795
14796
14797
14798
14799
14800
14801
14802
14803
14804
14805
14806
14807
14808
14809
14810
14811
14812
14813
14814
14815
14816
14817
14818
14819
14820
14821
14822
14823
14824
14825
14826
14827
14828
14829
14830
14831
14832
14833
14834
14835
14836
14837
14838
14839
14840
14841
14842
14843
14844
14845
14846
14847
14848
14849
14850
14851
14852
14853
14854
14855
14856
14857
14858
14859
14860
14861
14862
14863
14864
14865
14866
14867
14868
14869
14870
14871
14872
14873
14874
14875
14876
14877
14878
14879
14880
14881
14882
14883
14884
14885
14886
14887
14888
14889
14890
14891
14892
14893
14894
14895
14896
14897
14898
14899
14900
14901
14902
14903
14904
14905
14906
14907
14908
14909
14910
14911
14912
14913
14914
14915
14916
14917
14918
14919
14920
14921
14922
14923
14924
14925
14926
14927
14928
14929
14930
14931
14932
14933
14934
14935
14936
14937
14938
14939
14940
14941
14942
14943
14944
14945
14946
14947
14948
14949
14950
14951
14952
14953
14954
14955
14956
14957
14958
14959
14960
14961
14962
14963
14964
14965
14966
14967
14968
14969
14970
14971
14972
14973
14974
14975
14976
14977
14978
14979
14980
14981
14982
14983
14984
14985
14986
14987
14988
14989
14990
14991
14992
14993
14994
14995
14996
14997
14998
14999
15000
15001
15002
15003
15004
15005
15006
15007
15008
15009
15010
15011
15012
15013
15014
15015
15016
15017
15018
15019
15020
15021
15022
15023
15024
15025
15026
15027
15028
15029
15030
15031
15032
15033
15034
15035
15036
15037
15038
15039
15040
15041
15042
15043
15044
15045
15046
15047
15048
15049
15050
15051
15052
15053
15054
15055
15056
15057
15058
15059
15060
15061
15062
15063
15064
15065
15066
15067
15068
15069
15070
15071
15072
15073
15074
15075
15076
15077
15078
15079
15080
15081
15082
15083
15084
15085
15086
15087
15088
15089
15090
15091
15092
15093
15094
15095
15096
15097
15098
15099
15100
15101
15102
15103
15104
15105
15106
15107
15108
15109
15110
15111
15112
15113
15114
15115
15116
15117
15118
15119
15120
15121
15122
15123
15124
15125
15126
15127
15128
15129
15130
15131
15132
15133
15134
15135
15136
15137
15138
15139
15140
15141
15142
15143
15144
15145
15146
15147
15148
15149
15150
15151
15152
15153
15154
15155
15156
15157
15158
15159
15160
15161
15162
15163
15164
15165
15166
15167
15168
15169
15170
15171
15172
15173
15174
15175
15176
15177
15178
15179
15180
15181
15182
15183
15184
15185
15186
15187
15188
15189
15190
15191
15192
15193
15194
15195
15196
15197
15198
15199
15200
15201
15202
15203
15204
15205
15206
15207
15208
15209
15210
15211
15212
15213
15214
15215
15216
15217
15218
15219
15220
15221
15222
15223
15224
15225
15226
15227
15228
15229
15230
15231
15232
15233
15234
15235
15236
15237
15238
15239
15240
15241
15242
15243
15244
15245
15246
15247
15248
15249
15250
15251
15252
15253
15254
15255
15256
15257
15258
15259
15260
15261
15262
15263
15264
15265
15266
15267
15268
15269
15270
15271
15272
15273
15274
15275
15276
15277
15278
15279
15280
15281
15282
15283
15284
15285
15286
15287
15288
15289
15290
15291
15292
15293
15294
15295
15296
15297
15298
15299
15300
15301
15302
15303
15304
15305
15306
15307
15308
15309
15310
15311
15312
15313
15314
15315
15316
15317
15318
15319
15320
15321
15322
15323
15324
15325
15326
15327
15328
15329
15330
15331
15332
15333
15334
15335
15336
15337
15338
15339
15340
15341
15342
15343
15344
15345
15346
15347
15348
15349
15350
15351
15352
15353
15354
15355
15356
15357
15358
15359
15360
15361
15362
15363
15364
15365
15366
15367
15368
15369
15370
15371
15372
15373
15374
15375
15376
15377
15378
15379
15380
15381
15382
15383
15384
15385
15386
15387
15388
15389
15390
15391
15392
15393
15394
15395
15396
15397
15398
15399
15400
15401
15402
15403
15404
15405
15406
15407
15408
15409
15410
15411
15412
15413
15414
15415
15416
15417
15418
15419
15420
15421
15422
15423
15424
15425
15426
15427
15428
15429
15430
15431
15432
15433
15434
15435
15436
15437
15438
15439
15440
15441
15442
15443
15444
15445
15446
15447
15448
15449
15450
15451
15452
15453
15454
15455
15456
15457
15458
15459
15460
15461
15462
15463
15464
15465
15466
15467
15468
15469
15470
15471
15472
15473
15474
15475
15476
15477
15478
15479
15480
15481
15482
15483
15484
15485
15486
15487
15488
15489
15490
15491
15492
15493
15494
15495
15496
15497
15498
15499
15500
15501
15502
15503
15504
15505
15506
15507
15508
15509
15510
15511
15512
15513
15514
15515
15516
15517
15518
15519
15520
15521
15522
15523
15524
15525
15526
15527
15528
15529
15530
15531
15532
15533
15534
15535
15536
15537
15538
15539
15540
15541
15542
15543
15544
15545
15546
15547
15548
15549
15550
15551
15552
15553
15554
15555
15556
15557
15558
15559
15560
15561
15562
15563
15564
15565
15566
15567
15568
15569
15570
15571
15572
15573
15574
15575
15576
15577
15578
15579
15580
15581
15582
15583
15584
15585
15586
15587
15588
15589
15590
15591
15592
15593
15594
15595
15596
15597
15598
15599
15600
15601
15602
15603
15604
15605
15606
15607
15608
15609
15610
15611
15612
15613
15614
15615
15616
15617
15618
15619
15620
15621
15622
15623
15624
15625
15626
15627
15628
15629
15630
15631
15632
15633
15634
15635
15636
15637
15638
15639
15640
15641
15642
15643
15644
15645
15646
15647
15648
15649
15650
15651
15652
15653
15654
15655
15656
15657
15658
15659
15660
15661
15662
15663
15664
15665
15666
15667
15668
15669
15670
15671
15672
15673
15674
15675
15676
15677
15678
15679
15680
15681
15682
15683
15684
15685
15686
15687
15688
15689
15690
15691
15692
15693
15694
15695
15696
15697
15698
15699
15700
15701
15702
15703
15704
15705
15706
15707
15708
15709
15710
15711
15712
15713
15714
15715
15716
15717
15718
15719
15720
15721
15722
15723
15724
15725
15726
15727
15728
15729
15730
15731
15732
15733
15734
15735
15736
15737
15738
15739
15740
15741
15742
15743
15744
15745
15746
15747
15748
15749
15750
15751
15752
15753
15754
15755
15756
15757
15758
15759
15760
15761
15762
15763
15764
15765
15766
15767
15768
15769
15770
15771
15772
15773
15774
15775
15776
15777
15778
15779
15780
15781
15782
15783
15784
15785
15786
15787
15788
15789
15790
15791
15792
15793
15794
15795
15796
15797
15798
15799
15800
15801
15802
15803
15804
15805
15806
15807
15808
15809
15810
15811
15812
15813
15814
15815
15816
15817
15818
15819
15820
15821
15822
15823
15824
15825
15826
15827
15828
15829
15830
15831
15832
15833
15834
15835
15836
15837
15838
15839
15840
15841
15842
15843
15844
15845
15846
15847
15848
15849
15850
15851
15852
15853
15854
15855
15856
15857
15858
15859
15860
15861
15862
15863
15864
15865
15866
15867
15868
15869
15870
15871
15872
15873
15874
15875
15876
15877
15878
15879
15880
15881
15882
15883
15884
15885
15886
15887
15888
15889
15890
15891
15892
15893
15894
15895
15896
15897
15898
15899
15900
15901
15902
15903
15904
15905
15906
15907
15908
15909
15910
15911
15912
15913
15914
15915
15916
15917
15918
15919
15920
15921
15922
15923
15924
15925
15926
15927
15928
15929
15930
15931
15932
15933
15934
15935
15936
15937
15938
15939
15940
15941
15942
15943
15944
15945
15946
15947
15948
15949
15950
15951
15952
15953
15954
15955
15956
15957
15958
15959
15960
15961
15962
15963
15964
15965
15966
15967
15968
15969
15970
15971
15972
15973
15974
15975
15976
15977
15978
15979
15980
15981
15982
15983
15984
15985
15986
15987
15988
15989
15990
15991
15992
15993
15994
15995
15996
15997
15998
15999
16000
16001
16002
16003
16004
16005
16006
16007
16008
16009
16010
16011
16012
16013
16014
16015
16016
16017
16018
16019
16020
16021
16022
16023
16024
16025
16026
16027
16028
16029
16030
16031
16032
16033
16034
16035
16036
16037
16038
16039
16040
16041
16042
16043
16044
16045
16046
16047
16048
16049
16050
16051
16052
16053
16054
16055
16056
16057
16058
16059
16060
16061
16062
16063
16064
16065
16066
16067
16068
16069
16070
16071
16072
16073
16074
16075
16076
16077
16078
16079
16080
16081
16082
16083
16084
16085
16086
16087
16088
16089
16090
16091
16092
16093
16094
16095
16096
16097
16098
16099
16100
16101
16102
16103
16104
16105
16106
16107
16108
16109
16110
16111
16112
16113
16114
16115
16116
16117
16118
16119
16120
16121
16122
16123
16124
16125
16126
16127
16128
16129
16130
16131
16132
16133
16134
16135
16136
16137
16138
16139
16140
16141
16142
16143
16144
16145
16146
16147
16148
16149
16150
16151
16152
16153
16154
16155
16156
16157
16158
16159
16160
16161
16162
16163
16164
16165
16166
16167
16168
16169
16170
16171
16172
16173
16174
16175
16176
16177
16178
16179
16180
16181
16182
16183
16184
16185
16186
16187
16188
16189
16190
16191
16192
16193
16194
16195
16196
16197
16198
16199
16200
16201
16202
16203
16204
16205
16206
16207
16208
16209
16210
16211
16212
16213
16214
16215
16216
16217
16218
16219
16220
16221
16222
16223
16224
16225
16226
16227
16228
16229
16230
16231
16232
16233
16234
16235
16236
16237
16238
16239
16240
16241
16242
16243
16244
16245
16246
16247
16248
16249
16250
16251
16252
16253
16254
16255
16256
16257
16258
16259
16260
16261
16262
16263
16264
16265
16266
16267
16268
16269
16270
16271
16272
16273
16274
16275
16276
16277
16278
16279
16280
16281
16282
16283
16284
16285
16286
16287
16288
16289
16290
16291
16292
16293
16294
16295
16296
16297
16298
16299
16300
16301
16302
16303
16304
16305
16306
16307
16308
16309
16310
16311
16312
16313
16314
16315
16316
16317
16318
16319
16320
16321
16322
16323
16324
16325
16326
16327
16328
16329
16330
16331
16332
16333
16334
16335
16336
16337
16338
16339
16340
16341
16342
16343
16344
16345
16346
16347
16348
16349
16350
16351
16352
16353
16354
16355
16356
16357
16358
16359
16360
16361
16362
16363
16364
16365
16366
16367
16368
16369
16370
16371
16372
16373
16374
16375
16376
16377
16378
16379
16380
16381
16382
16383
16384
16385
16386
16387
16388
16389
16390
16391
16392
16393
16394
16395
16396
16397
16398
16399
16400
16401
16402
16403
16404
16405
16406
16407
16408
16409
16410
16411
16412
16413
16414
16415
16416
16417
16418
16419
16420
16421
16422
16423
16424
16425
16426
16427
16428
16429
16430
16431
16432
16433
16434
16435
16436
16437
16438
16439
16440
16441
16442
16443
16444
16445
16446
16447
16448
16449
16450
16451
16452
16453
16454
16455
16456
16457
16458
16459
16460
16461
16462
16463
16464
16465
16466
16467
16468
16469
16470
16471
16472
16473
16474
16475
16476
16477
16478
16479
16480
16481
16482
16483
16484
16485
16486
16487
16488
16489
16490
16491
16492
16493
16494
16495
16496
16497
16498
16499
16500
16501
16502
16503
16504
16505
16506
16507
16508
16509
16510
16511
16512
16513
16514
16515
16516
16517
16518
16519
16520
16521
16522
16523
16524
16525
16526
16527
16528
16529
16530
16531
16532
16533
16534
16535
16536
16537
16538
16539
16540
16541
16542
16543
16544
16545
16546
16547
16548
16549
16550
16551
16552
16553
16554
16555
16556
16557
16558
16559
16560
16561
16562
16563
16564
16565
16566
16567
16568
16569
16570
16571
16572
16573
16574
16575
16576
16577
16578
16579
16580
16581
16582
16583
16584
16585
16586
16587
16588
16589
16590
16591
16592
16593
16594
16595
16596
16597
16598
16599
16600
16601
16602
16603
16604
16605
16606

In [23]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hillari',
 'chuck todd buzzfe donald trump polit favor breitbart',
 'monica lewinski clinton sex scandal set american crime stori',
 'rob reiner trump mental unstabl breitbart',
 'abort pill order rise latin american nation zika alert new york time',
 'nuke un histor treati ban nuclear weapon',
 'exclus islam state support vow shake west follow manchest terrorist massacr breitbart',
 'humili hillari tri hide camera caught min ralli',
 'andrea tantaro fox news claim retali sex harass complaint new york time',
 'hillari clinton becam hawk new york time',
 'chuck todd buzzfe eic publish fake news breitbart',
 'bori johnson brexit leader fumbl new york time',
 'texa oil field rebound price lull job left behind new york time',
 'bayer deal monsanto follow agribusi trend rais worri farmer new york time',
 'russia move ban jehovah wit extremist new york time',
 'still danger zone januari th',
 'open thread u elect',
 'democrat gutierrez blame chicago gun violenc nra breitbart',
 'avoid peanut avoid allergi bad strategi new york time',
 'mri show detail imag week unborn babi breitbart',
 'best kind milk dairi',
 'ryan locht drop speedo usa retail new york time',
 'conserv urg session clean obama civil right divis breitbart',
 'intern inquiri seal fate roger ail fox new york time',
 'press tv debat duff lebanon hezbollah aoun presid video',
 'samsung combust galaxi note unveil new smartphon new york time',
 'poland vow referendum migrant quota amidst eu pressur public voic heard breitbart',
 'spark inner revolut',
 'studi half car crash involv driver distract cell phone breitbart',
 'trump elect spark individu collect heal',
 'ep fade black jimmi church w laura eisenhow restor balanc video',
 'cognit true islam book review',
 'donald trump win elect biggest miracl us polit histori',
 'mind eat way fight bing new york time',
 'major potenti impact corpor tax overhaul new york time',
 'wonder glp like day elect',
 'maker world smallest machin award nobel prize chemistri new york time',
 'massiv anti trump protest union squar nyc live stream',
 'review lion bring tear lost boy wipe dri googl new york time',
 'u gener islam state chemic attack impact u forc',
 'juri find oregon standoff defend guilti feder conspiraci gun charg',
 'clinton campaign stun fbi reportedli reopen probe hillari clinton email',
 'penc speak anti abort ralli new york time',
 'berni sander say media trump gutless polit coward',
 'make briquett daili wast',
 'treason nyt vow reded report',
 'dress like woman mean new york time',
 'ella brennan still feed lead new orlean new york time',
 'press asia agenda obama tread lightli human right new york time',
 'democrat percent chanc retak senat new york time',
 'judg spank transgend obsess obama lie redflag news',
 'u diplomat urg strike assad syria new york time',
 'franken call independ investig trump putin crush breitbart',
 'louisiana simon bile u presidenti race tuesday even brief new york time',
 'turkey threaten open migrant land passag europ row dutch',
 'huma weiner dog hillari',
 'colin kaepernick start black panther inspir youth camp wow',
 'trump immigr polici explain new york time',
 'mari tyler moor mourn dick van dyke star new york time',
 'poison',
 'trump fan ralli across nation support presid new york time',
 'fox biz report help bash clinton ralli cover trump pack event day',
 'fiction podcast worth listen new york time',
 'mike birbiglia tip make small hollywood anywher new york time',
 'invest strategist forecast collaps timelin last gasp econom cycl come',
 'venezuela muzzl legislatur move closer one man rule new york time',
 'whether john mccain mitt romney donald trump democrat alway run war women tactic destroy republican candid',
 'breitbart news daili trump boom breitbart',
 'white hous confirm gitmo transfer obama leav offic',
 'poll voter heard democrat elect candid breitbart',
 'migrant confront judgment day old deport order new york time',
 'n u yale su retir plan fee new york time',
 'technocraci real reason un want control internet',
 'american driver regain appetit ga guzzler new york time',
 'hillari clinton build million war chest doubl donald trump new york time',
 'trump catch sick report snuck interview priceless respons',
 'senat contact russian govern week',
 'imag perfectli illustr struggl dakota access pipelin',
 'washington state take refuge muslim rest countri take refuge muslim breitbart',
 'ncaa big keep watch eye texa bathroom bill breitbart',
 'massiv espn financi subscrib loss drag disney first quarter sale breitbart',
 'megyn kelli contract set expir next year prime big show new york time',
 'teacher suspend allow student hit trump pinata cinco de mayo',
 'break trump express concern anthoni weiner illeg access classifi info month ago truthfe',
 'snap share leap debut investor doubt valu vanish new york time',
 'clinton campaign chair dinner top doj offici one day hillari benghazi hear',
 'tv seri first femal mlb pitcher can one low rate season breitbart',
 'seek best fit women final four return friday sunday new york time',
 'propos canadian nation bird ruffl feather new york time',
 'review beyonc make lemonad marit strife new york time',
 'trump ask sharp increas militari spend offici say new york time',
 'waterg smoke gun email discuss clean obama hillari email',
 'chapo trap hous new left wing podcast flagrant rip right stuff',
 'taiwan respond china send carrier taiwan strait new york time',
 'mother octob surpris hous card come tumbl',
 'explos assang pilger interview us elect expect riot hillari win',
 'telescop ate astronomi track surpass hubbl new york time',
 'close afghan pakistani border becom humanitarian crisi new york time',
 'tv anchor arriv white hous lunch donald trump breitbart',
 'pelosi republican tell trump bring dishonor presid breitbart',
 'beauti prehistor world earth wasteland',
 'ignor trump news week learn new york time',
 'donald trump unveil plan famili bid women vote new york time',
 'montana democrat vote bill ban sharia law call repugn breitbart',
 'monsanto tribun go happen',
 'offici simon bile world best gymnast new york time',
 'liter hurt brain read econom idioci emit trumpkin libertarian',
 'u n secretari gener complain mass reject global favor nation',
 'trump bollywood ad meant sway indian american voter hilari fail video',
 'fbi find previous unseen hillari clinton email weiner laptop',
 'year american journalist kill conspiraci theori syria proven fact',
 'report illeg alien forego food stamp stay trump radar',
 'make netherland great hahaha spread worldwid',
 'four kill injur jerusalem truck ram terror attack',
 'leader salut comrad newt brutal megyn sic kelli beatdown play game',
 'student black colleg got beaten mace protest kkk david duke',
 'despit strict gun control one child youth shot everi day ontario',
 'rise internet fan bulli new york time',
 'newli vibrant washington fear trump drain cultur new york time',
 'fed hold interest rate steadi plan slower increas new york time',
 'battl unesco',
 'latest test white hous pull easter egg roll new york time',
 'burlesqu dancer fire investig secret servic trump assassin tweet breitbart',
 'clinton haiti',
 'cuomo christi parallel path top troubl got new york time',
 'top place world allow visit',
 'new studi link fluorid consumpt hypothyroid weight gain wors',
 'jame matti secretari offens',
 'black church burn spray paint vote trump',
 'sear agre sell craftsman stanley black amp decker rais cash new york time',
 'takata chief execut resign financi pressur mount new york time',
 'goodby good black sabbath new york time',
 'teen geisha doll gang bust arm robberi breitbart',
 'mohamad khwei anoth virginia man palestinian american muslim charg terror',
 'price obamacar replac nobodi wors financi breitbart',
 'va fail properli examin thousand veteran',
 'trump famili alreadi sworn secreci fake moon land soon',
 'sport writer nfl great jim brown decad civil right work eras say nice thing donald trump breitbart',
 'watch tv excus republican skip donald trump convent new york time',
 'open letter trump voter told like',
 'comment power corpor lobbi quietli back hillari nobodi talk runsinquicksand',
 'hijack end peac libyan airlin land malta new york time',
 'like girl girl geniu new york time',
 'scientist say canadian bacteria fossil may earth oldest new york time',
 'pro govern forc advanc syria amid talk u russia cooper new york time',
 'cancer agenc fire withhold carcinogen glyphos document',
 'work walk minut work new york time',
 'steve harvey talk hous presid elect trump new york time',
 'coalit u troop fight mosul offens come fire',
 'uk citizen war hero get cheap pre fab hous muslim colon get taxpay fund luxuri council home',
 'vet fight war fed demand money back illeg refuge keep money',
 'mr trump wild ride new york time',
 'fbi director comey bamboozl doj congress clinton',
 'food natur unclog arteri prevent heart attack',
 'death two state solut',
 'comment parent date asleep car cop arriv kill facespac',
 'donald trump team show sign post elect moder new york time',
 'miami beach tri tame raucou street fishbowl drink stay new york time',
 'doctor mysteri found dead summit breakthrough cure cancer',
 'donald trump unsink candid new york time',
 'shock new mock hillari ad campaign warn take us war enlistforh fightforh dieforh',
 'exclus famili slain border patrol agent brian terri say eric holder among real crimin respons',
 'trump tell report wall work ask israel breitbart',
 'america surviv next year',
 'commission start press cleveland indian logo new york time',
 'un plan implant everyon biometr id drill',
 'trump attack senat credibl gorsuch comment new york time',
 'clinton advisor lose leak email hillari illeg activ',
 'art laffer paul ryan perfect right breitbart',
 'donald trump blame econom crash',
 'pokemon go player inadvert stop peopl commit suicid japan',
 'california senat race tale divers flail g p new york time',
 'exclus sourc say megyn kelli would welcom back fox news',
 'break preced obama envoy deni extens past inaugur day new york time',
 'brexit vote go monti python may offer clue new york time',
 'blind mystic predict bad news trump',
 'total vet fail left wing snowden fan girl realiti winner get access nsa secret',
 'somalia u escal shadow war new york time',
 'free care bless victim orlando nightclub attack new york time',
 'durabl democrat counti countri could go trump',
 'fed challeng rais rate may existenti new york time',
 'russia intent attack anyon absurd say vladimir putin',
 'f investig errant flight involv harrison ford new york time',
 'fed rais key interest rate cite strengthen economi new york time',
 'la expresi n lo siguient ya es la utilizada lo siguient en el castellano',
 'trump berat news media new strategi need cover new york time',
 'u drone strike target taliban leader new york time',
 'u intellig expect al qaeda attack monday new york virginia texa',
 'told cannabi great revers alzheim',
 'report megyn kelli kick nbc show kardashian famili interview',
 'local percent may rich think new york time',
 'dr david duke mark collett uk collett explain duke trump victori would chang polit forev',
 'statement senat well fargo chief deepli sorri new york time',
 'cnn statement distanc network buzzfe fake news dossier breitbart',
 'c e ponder new game trump rule new york time',
 'spicer bradi stolen jersey anoth bad press breitbart',
 'scaredi cat investig peopl enjoy fear new york time',
 'left vision',
 'showdown loom u question chines deal german chip design new york time',
 'trump administr take harder tack trade china new york time',
 'pew american trust level feder govern plummet histor low breitbart',
 'islam state support former nation guardsman plead guilti terror charg virginia',
 'spicer report go rais hand like big boy girl breitbart',
 'leader applaud gorsuch confirm win pro life movement',
 'newstick',
 'french vogu march cover featur transgend model new york time',
 'trump veer parti line gun control new york time',
 'oligarchi prepar groundwork steal elect',
 'ya hay reencuentro de operaci n triunfo que edicion de operaci n triunfo',
 'chatsworth hous tale five centuri new york time',
 'uncomfort love affair donald trump new england patriot new york time',
 'john mccain withdraw support donald trump disclosur record new york time',
 'strang unend limbo egypt hosni mubarak new york time',
 'poverti rose u hous district obama presid',
 'huma abedin seek fbi immun deal',
 'singl mom escap friend zone one non date time new york time',
 'boe suit futur spaceflight new spacesuit design breitbart',
 'trump float oliv branch might keep part health law new york time',
 'wapo tri compar elizabeth warren break senat rule milo shut violent riot breitbart',
 'crumpl school bu leav chattanooga daze new york time',
 'die came back life incred messag human',
 'fight nation african american museum new york time',
 'father manchest suicid bomber arrest libya breitbart',
 'secret true leader',
 'muslim demand local walk dog public violat sharia disrespect',
 'hillari campaign bed pac staff donat k fbi agent wife investig',
 'still tri flip elector colleg block trump win',
 'al sharpton dem point appeal archi bunker trump voter breitbart',
 'think mani doom sayer trump get offic',
 'democrat jump session resign band wagon breitbart',
 'alt right architect glenn beck open fire alt right grave threat republ audio tweet',
 'politic justic protect hillari',
 'north carolina satur surpris reel hurrican matthew new york time',
 'live love submit memori new york time',
 'achiev mind work medit cushion requir new york time',
 'world first zero emiss hydrogen power passeng train unveil germani',
 'confus chip credit card get line new york time',
 'brook trump side foreign leader us presid israel russia breitbart',
 'toxic air home get rid natur',
 'connecticut reader report record voter registr inspir trump',
 'germani react merkel trump visit could lot wors new york time',
 'justin rose outduel henrik stenson golf gold medal new york time',
 'iceland water cure new york time',
 'shorten l train shutdown month new york time',
 'time presid decid new york time',
 'u n relief offici call crisi aleppo apex horror new york time',
 'berkeley treat violent anti speech left like kkk',
 'statist propaganda mani syrian us regim chang kill',
 'self help guru jame altuch own thing new york time',
 'trump religi liberti order give session major leeway breitbart',
 'demoledor amparo contra salgado keiko congresista',
 'era trump china presid champion econom global new york time',
 'sad saga john walker lindh rebel without clue',
 'court disagre michigan vote recount new york time',
 'berni sander feud democrat leadership heat new york time',
 'shortest power explan trump victori ever seen',
 'russia look popul far east wimp need appli new york time',
 'johnson amend trump vow destroy explain new york time',
 'donald trump march life full support',
 'polic offici found dead long island suicid suspect new york time',
 'radic chang store world global market readi',
 'like make showbiz best friend new york time',
 'trump nomin neil gorsuch suprem court new york time',
 'bidder cast doubt serious mexican border wall project',
 'stake us elect',
 'israel approv addit fund settlement west bank new york time',
 'tx gov abbott sign legisl could put sheriff sanctuari citi jail breitbart',
 'donald trump hold thank ralli cincinnati announc pick defens secretari new york time',
 'lawmak look bipartisanship health care new york time',
 'insid conserv push state amend constitut new york time',
 'donald trump tell n r hillari clinton want let violent crimin go free new york time',
 'pope franci trump japan tuesday brief new york time',
 'mayorsstand day tout support illeg immigr',
 'trump campaign celebr',
 'democrat drag jeff session confirm fight breitbart',
 'break news podesta brother pedo ring mr trump drain swamp v guerrilla economist',
 'la frase destacada del debat de investidura',
 'confus jihad hirabah build peac world',
 'lazi liber journalist smear bannon',
 'australia close detent center manu island still accept asylum seeker new york time',
 'politico hillari clinton run breitbart',
 'giant lynx make ador sound whenev human rub face',
 'minnesota cop found guilti philando castil shoot trial',
 'million american kill minut',
 'wayn madsen cia alway serv interest wall street',
 'novemb daili contrarian read',
 'flashback report obama campaign rep talk iran hama',
 'lesseroftwoevil',
 'aya cash first time ate veget new york time',
 'trump advis say isra settlement illeg',
 'serena william prevail open problem new york time',
 'soul man sam moor honor perform trump inaugur',
 'ferrel came back bush destroy trump video',
 'chines govern concern tough talk trump cabinet breitbart',
 'billionair report seiz hong kong hotel taken china new york time',
 'easi know link',
 'homebodi find ultim home offic new york time',
 'ann coulter unload paul ryan deepli unpopular obamacar bill breitbart',
 'transgend bathroom debat turn person vermont high school new york time',
 'obama hillari want libya gaddafi toppl kill',
 'alert former soro associ warn pro wrong gold silver skyrocket like',
 'hillari panick fbi weiner email',
 'chaotic minut trump defend fine tune machin new york time',
 'one polic shift patrol anxiou america new york time',
 'fight ghost fascist aid real one',
 'monday even brief brexit abort game throne new york time',
 'eu increas brexit bill demand billion billion',
 'arianna huffington sleep revolut start home new york time',
 'iranian missil accident destroy iranian ship aim syria',
 'sonoma counti california vote creat largest gmo free zone america',
 'fbi comey wikileak intellig porn journal breitbart',
 'clare waight keller name first femal design givenchi new york time',
 'realiti face black canadian nation shame',
 'top nfl draft prospect caleb brantley charg punch woman face breitbart',
 'video pacif crest trail associ lavoy finicim murder',
 'life lesson man seen death',
 'trump g p work win repeal obama health act new york time',
 'atlant goldberg confid trump handl matter life death breitbart',
 'orthodox rabbi support trump',
 'nuclear tension us russia reach danger point',
 'gambia join south africa burundi exodu intern crimin court',
 'peyton man golf presid trump sunday',
 'obama urg donald trump send signal uniti minor group women new york time',
 'like miracl woman give birth use ovari frozen sinc childhood new york time',
 'uconn recip success run run run new york time',
 'assang final afford opportun give statement rape accus',
 'hillari puppet show much hillari care god omiss word',
 'stock market gone high problem new york time',
 'john kerri reject suggest u involv turkey coup new york time',
 'trump aid stephen miller u absolut sovereign right determin cannot enter countri breitbart',
 'year old russian girl speak languag',

In [24]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[3031, 167, 3408, 2295, 1099, 476, 3144, 948, 4093, 3483],
 [4354, 2489, 4339, 4994, 760, 2216, 4034],
 [2310, 1624, 1547, 4439],
 [2713, 4989, 546, 4946, 4964, 3935],
 [1468, 760, 356, 1512, 4563, 3618, 760, 1943, 4680, 934],
 [1092,
  1619,
  2734,
  1569,
  4411,
  3431,
  4847,
  2353,
  2901,
  729,
  4871,
  3612,
  418,
  1574,
  4034],
 [4983, 2680, 1306, 2053, 3559, 995, 2915, 4016, 681, 1595, 906],
 [4744, 2126, 2994, 2446, 3501, 4410, 3431, 2281, 681, 1595, 906],
 [1787, 2632, 1194, 2042, 3070, 260, 4209, 78, 3431, 1400],
 [2316, 4433, 4225, 2642, 1828, 3435, 1976, 2331],
 [3425, 4294, 793, 3804, 2911, 3326, 4870, 4946, 996, 1906, 3814],
 [4946, 3465, 1099, 260, 3431, 3501],
 [4597, 1493, 4772, 1101, 2469, 2137, 4436, 3840, 2286],
 [2644, 2858, 4609, 128, 1754, 1377, 1901, 681, 1595, 906],
 [4337, 3416, 3544, 538, 1975, 681, 1595, 906],
 [4195, 1303, 4246, 3149, 2656, 3458, 3070, 4352, 4010, 2257],
 [1497, 812, 2489],
 [1288, 3339, 3871, 1971, 3431, 675, 3079, 4034],
 [1300, 3803, 4339, 2312, 4485, 3834, 2913, 4926, 3618],
 [4353, 1351, 3431, 4379, 2264, 4034],
 [3182, 2868, 4415, 1288, 3897, 2913, 2301, 456, 1647, 681, 1595, 906],
 [1115, 707, 4915, 423, 4250, 540, 1743],
 [418, 3183, 965, 960, 1997, 2567, 3393, 145, 3584, 1501, 2540, 4034],
 [3260, 2489, 3608, 1237, 2263, 3752, 3618, 3936],
 [4631, 1549, 710, 2066, 4066, 1805, 2312, 3576, 3320, 681, 1595, 906],
 [2489, 4339, 2026, 4971, 681, 1595, 906],
 [1288, 3339, 3871, 370, 2752, 2585, 2066, 4034],
 [4399, 2948, 1967, 1200, 4624, 681, 1595, 906],
 [3625, 2490, 4107, 371, 1165, 3753, 2515, 1442, 134, 681, 1595, 906],
 [2670, 3965, 4386, 145, 657, 2120, 770, 208, 552, 681, 1595, 906],
 [3501, 2367, 4250, 3581, 4378, 2677, 681, 1595, 906],
 [3658, 1420, 2298, 428, 2609],
 [701, 3547, 1722, 1144],
 [908, 1323, 3490, 1355, 4780, 4340, 4339, 4034],
 [3157, 2461, 3157, 4228, 4466, 4181, 681, 1595, 906],
 [4529, 3982, 3548, 2187, 993, 465, 4903, 4034],
 [1209, 4178, 493, 3626],
 [3626, 4788, 1851, 3117, 2192, 1832, 681, 1595, 906],
 [1333, 2927, 3547, 4389, 1787, 4428, 3389, 3801, 4034],
 [4523, 3144, 3490, 4895, 2753, 2051, 710, 681, 1595, 906],
 [3534, 4982, 1658, 1298, 2889, 4857, 65, 1221, 1574],
 [420, 3840, 2629, 2848, 4844, 681, 905, 681, 1595, 906],
 [4757, 1997, 3516, 915, 3301, 2385, 2681, 428, 4715, 2751, 2924, 4034],
 [4658, 4624, 2342],
 [4555, 610, 990, 2164, 1295, 358, 3959, 479, 3762, 4034],
 [3431, 1144, 4658, 1467, 4353, 528],
 [2712, 1011, 3755, 1793, 364, 3929, 3998, 3643, 2672, 3380, 1574],
 [4202, 1414, 3183, 3454, 2725],
 [1971, 3431, 1306, 1144, 1522, 830, 4946, 675, 1891],
 [3777, 157, 4607, 3986, 474, 681, 1595, 906],
 [2644, 2587, 4297, 1900, 180, 3654, 681, 1595, 906],
 [2060, 2800, 557, 1298, 1144],
 [4370, 3216, 110, 2721, 2511, 4259, 1062, 4759, 681, 1595, 906],
 [3082, 269, 3431, 1508, 3419, 3505, 4833, 569, 797],
 [2725, 3224, 2421, 1102, 3792, 1923, 4799, 757, 3995, 681, 1595, 906],
 [1722, 1570, 3183, 965, 280, 3014, 4297, 1722, 2861],
 [2690, 1754, 3773, 2909, 2455, 4331, 1211, 3188, 4780, 3994],
 [4339, 180, 1307, 1497, 2944, 1571, 2046, 2489, 4339, 1659],
 [451, 1141, 269, 3182, 3936, 681, 1595, 906],
 [4630, 1107, 1371, 2137, 3431, 2302, 675, 3742],
 [2856, 4030, 1242, 3813],
 [1627, 3037, 1997, 162, 22],
 [2357, 557, 760, 1465, 681, 1595, 906],
 [76, 901, 3658, 280, 4226, 681, 608, 681, 1595, 906],
 [3534, 3488, 1400, 1787, 4171, 751, 432, 3389, 681, 1595, 906],
 [908, 680, 4604, 1484, 4471, 681, 1595, 906],
 [4132, 4964, 1577, 256, 1787, 1135, 1511, 2066],
 [1722, 1931, 2927, 1019, 228, 749, 681, 1595, 906],
 [2069, 3651, 2102, 2075, 3431, 4516, 3332, 4034],
 [126, 4932, 2120, 1722, 2915, 574, 3080, 2295, 3066, 681, 1595, 906],
 [488, 4272, 701, 915, 4242, 2404, 1047, 4897, 1102],
 [4842, 1446, 3376, 2489],
 [3719, 92, 4324, 3755, 4981, 2226, 3758, 2581, 4188],
 [3431, 2097, 4592, 3422, 681, 1595, 906],
 [3420, 3242, 378, 1405, 1366, 2560, 1046, 403, 681, 1595, 906],
 [4811],
 [3431, 4152, 3936, 4360, 2301, 960, 1221, 681, 1595, 906],
 [710, 2241, 22, 2434, 4756, 4339, 3936, 1519, 3431, 2075, 4388, 1298],
 [1512, 2040, 36, 274, 681, 1595, 906],
 [4188, 1378, 977, 2856, 3827, 2734, 2760, 681, 1595, 906],
 [4632, 1627, 1242, 251, 2368, 2484, 4562, 3326, 4486, 2297],
 [3425, 3879, 827, 2367, 4376, 854, 4403, 1234, 681, 1595, 906],
 [4533,
  3367,
  574,
  4177,
  4296,
  1971,
  3431,
  908,
  4595,
  4466,
  2071,
  4482,
  1526,
  2435,
  1943,
  1838],
 [4034, 2066, 1242, 3431, 1087, 4034],
 [2248, 3031, 2313, 2697, 3595, 1787, 2159, 4769],
 [3200, 2989, 2924, 908, 1144, 1838, 4034],
 [915, 2356, 4304, 1298, 11, 2920, 4415, 681, 1595, 906],
 [4362, 1722, 4654, 903, 640, 2994, 2691, 681, 1595, 906],
 [122, 2642, 4728, 707, 4828, 2306, 3234],
 [2913, 358, 303, 2785, 290, 2083, 681, 1595, 906],
 [2489, 4339, 3268, 3149, 2071, 3850, 4968, 1971, 3431, 681, 1595, 906],
 [3431, 3501, 4776, 22, 1689, 345, 4075, 2506],
 [4471, 2612, 3425, 4772, 993],
 [2187, 451, 1854, 4286, 4352, 4010, 2257],
 [728, 965, 4098, 392, 276, 4421, 4998, 4098, 392, 276, 4034],
 [448, 4994, 3184, 801, 2046, 3625, 3612, 636, 4034],
 [3082, 2795, 2380, 1006, 994, 1313, 3551, 3063, 3385, 280, 4034],
 [2273, 2036, 3338, 3834, 1383, 1884, 1522, 2055, 4994, 3982, 681, 1595, 906],
 [2357, 1694, 4016, 4871, 886, 3431, 3254, 2873, 779, 2347],
 [1657, 3431, 358, 4677, 2473, 1446, 4403, 4010, 1917, 4341, 1776, 1831, 2078],
 [2466, 2879, 1409, 1117, 112, 1340, 752, 3807, 681, 1595, 906],
 [4339, 180, 3680, 304, 148, 2870, 3465, 854, 1298, 2489, 3437, 4498],
 [4982, 4890, 3063, 1214, 548, 643, 3406, 854, 425, 2069, 964, 4034],
 [2734, 1209, 1898, 4482, 717, 3096, 2907, 1603, 1716, 681, 1595, 906],
 [4853, 1017, 2301, 3326, 2049, 3529, 681, 1595, 906],
 [2725, 2671, 2856, 111, 214, 1105, 681, 1595, 906],
 [3431, 1835, 198, 2665, 3326, 930, 3465, 1371, 681, 1595, 906],
 [3292, 3459, 4780, 1659, 246, 4389, 1787, 2489, 1659],
 [4233, 1033, 3031, 681, 1442, 1465, 2040, 3965, 2993, 3389, 777],
 [4180, 672, 1675, 1110, 2827, 4180, 4882, 681, 1595, 906],
 [782, 2109, 2431, 3031, 2876, 2297, 342],
 [4266, 134, 607, 345, 4946, 1144, 332, 4783, 2489, 1306],
 [4043, 2891, 2259, 4446, 513, 1004, 681, 1595, 906],
 [812, 976, 1795, 2676, 4997, 673, 988, 681, 1595, 906],
 [4982, 4166, 579, 2248, 3031, 1107, 1971, 3431, 4034],
 [854, 1943, 3115, 3431, 2421, 2570, 1221, 4034],
 [3531, 282, 3216, 856, 274],
 [3965, 3431, 2066, 993, 1501, 681, 1595, 906],
 [1971, 3431, 4844, 2994, 1703, 2875, 4482, 4929, 681, 1595, 906],
 [1931, 908, 4929, 636, 4250, 1225, 3553, 3651, 3115, 4034],
 [4386, 3900, 855, 2175],
 [3465, 4932, 2120, 3216, 1209, 528, 681, 1595, 906],
 [2403, 2799, 1144, 3031, 3326, 1473, 1873, 2268, 1484],
 [1722, 4362, 4761, 1570, 3214, 2023, 3315, 1961, 3079, 2301],
 [3431, 558, 2190, 2647, 3340, 2905, 2913, 2989, 151, 901, 1574],
 [1497, 1754, 3597, 3028, 2489, 4339, 1659, 1446, 4644],
 [1522, 2913, 190, 4989, 3188, 2933, 749, 4995, 3596],
 [22, 4403, 2684, 3891, 1507, 303, 2515, 3431, 1420],
 [2856, 3002, 2348, 1706, 1039, 3559],
 [3096, 4989, 1156, 4179, 3788, 2190, 3686, 3014],
 [1200, 1035, 2308, 4852, 1173, 2273, 410, 2036, 2297, 884, 1849],
 [4871, 3755, 928, 59, 787, 356, 1508, 2635, 2997, 3959],
 [2648, 4669, 4780, 2306, 854, 3281, 3758, 512, 4285, 1298, 4342],
 [1288, 3234, 4152, 3107, 681, 1595, 906],
 [518, 4681, 728, 1750, 3431, 2794, 2701, 681, 1595, 906],
 [443, 163, 2249, 2069, 266, 2994, 3866, 2665, 681, 1595, 906],
 [3896, 4709],
 [4589, 3300, 2248, 3031, 1709, 4065, 1319, 3094, 681, 1595, 906],
 [217, 3190, 4439, 2075, 3804, 4674, 3431, 62, 3483, 4034],
 [4339, 929],
 [2066, 4631, 1490, 4498, 148, 2563, 59, 681, 1595, 906],
 [148, 4204, 3216, 4016, 2604],
 [681, 4555, 260, 4553, 1078, 4150, 2212, 224, 2525],
 [281, 2113, 4761, 75],
 [3755, 364, 3800, 2873, 1028, 4929, 3431],
 [1068, 981, 356, 1780, 2212, 3755, 3514, 3323, 770, 418, 681, 1595, 906],
 [3479, 3544, 3850, 3294, 2380, 428, 962, 681, 1595, 906],
 [2802, 1260, 3755, 2032, 681, 1595, 906],
 [790, 1851, 4135, 4612, 1223, 92, 930, 4034],
 [2752, 826, 4629, 3722, 4403, 918, 2913, 276, 3994, 3686],
 [1165, 4074, 489, 383, 2525, 2380, 4034],
 [2130, 901, 1484, 3991, 952, 175],
 [3431, 1703, 4992, 1007, 167, 2585, 1241, 4242, 113],
 [2299,
  3388,
  4424,
  2348,
  4671,
  2269,
  513,
  4428,
  3389,
  4632,
  2826,
  1371,
  943,
  4157,
  1971,
  3431,
  4034],
 [801, 4982, 2670, 1943, 513, 1971, 3431, 3582, 681, 1595, 906],
 [701, 3144, 3431, 2989, 4014, 557],
 [3059, 461, 1900, 2081, 3097, 4744, 2489, 383, 3459, 2915],
 [2525, 3916, 257, 1491, 4837, 4242, 3053, 681, 1595, 906],
 [557, 2497, 2497, 2901, 681, 1595, 906],
 [4560, 1371, 1017, 2951, 2293, 2243, 856, 797, 681, 1595, 906],
 [2920, 4772, 2861, 1590, 749, 2090, 3459, 1722, 3501, 4293, 681, 1595, 906],
 [18, 3463, 4439, 3018, 3873, 4599, 4408],
 [4632, 4465, 1689, 4632, 681, 1595, 906],
 [2329, 385, 3459, 3031, 1221, 1144, 3431, 681, 1595, 906],
 [4090, 1722, 1995, 3986, 428, 75, 2297, 4439],
 [2108,
  4833,
  2071,
  4117,
  1547,
  1194,
  1854,
  1571,
  3031,
  276,
  2730,
  1547,
  3278,
  1792,
  1424,
  785,
  1377],
 [2977, 3986, 2071, 443, 3631, 1425, 4744, 4403, 392, 3184, 1425],
 [4588, 3431, 2013, 912, 681, 1595, 906],
 [1497, 2937, 476, 1370, 2870, 867, 4339],
 [1507, 3475, 2280, 3579, 4458, 1814, 3014],
 [4680, 761, 965, 1581],
 [3059, 868, 3275, 4216, 990, 2790, 579, 4989, 2334],
 [1971, 3431, 4171, 3982, 3472, 1109, 1144, 2483, 681, 1595, 906],
 [1298, 3510, 3608, 3514, 1667, 4020, 2520, 3724, 2515, 681, 1595, 906],
 [676, 1821, 3597, 154, 2780, 2794, 2651, 18],
 [1971, 3431, 3630, 1838, 681, 1595, 906],
 [1132, 681, 2650, 2489, 2190, 180, 859, 4098, 4946, 2071, 4009, 216, 4577],
 [418,
  1703,
  3382,
  2676,
  479,
  2142,
  1458,
  806,
  1371,
  3065,
  3397,
  1139,
  2642,
  1378,
  2506],
 [3431, 3115, 22, 4988, 4632, 1835, 892, 4034],
 [1508, 4905, 1884, 1522],
 [3888, 4324, 3534, 1680, 2905, 485, 681, 1595, 906],
 [707, 2994, 2421, 3458, 1323, 862, 1421],
 [3431, 3014, 4471, 4756, 2530, 3059, 681, 1595, 906],
 [4339, 4593, 2230, 4082, 1659, 2489, 4403, 56],
 [3761, 1825, 1743, 3626, 4913, 3389, 4034],
 [1971, 3431, 3490, 3326, 2164],
 [1762, 855, 499, 1175, 1320, 260, 4076, 396, 16],
 [4053, 4471, 574, 2775, 3674, 892, 4134, 2337, 681, 1595, 906],
 [418, 2632, 1371, 2273, 2036, 1569, 1773, 4744, 710, 2066],
 [1657, 644, 1787, 3022, 53, 1525, 4303, 4152, 1298, 681, 1595, 906],
 [1967, 4929, 855, 3484, 4606, 2243, 2952, 2641, 681, 1595, 906],
 [4831, 1480, 29, 4466, 2066, 3431],
 [2025,
  2977,
  901,
  1442,
  1465,
  831,
  4152,
  2497,
  1037,
  1932,
  1547,
  4010,
  3447,
  3804],
 [4465, 1722, 19, 4565, 2071, 681, 1595, 906],
 [2460, 3624, 1567, 3673, 3420, 2701, 3014, 681, 1595, 906],
 [3210, 908, 79, 4998, 3607, 855, 3431],
 [443, 3394, 770, 2069, 2243, 856, 681, 1595, 906],
 [3501, 2974, 3014, 3909, 4117, 1371, 859, 4516],
 [4295, 2075, 2615, 1762, 1295, 1688, 1483, 681, 1595, 906],
 [443, 770, 88, 2249, 2069, 619, 4383, 1028, 681, 1595, 906],
 [1686,
  3784,
  4362,
  3713,
  3795,
  3809,
  3359,
  1686,
  3060,
  3713,
  3795,
  3509,
  2119,
  1273],
 [3431, 1037, 2066, 2137, 681, 4181, 1212, 1519, 681, 1595, 906],
 [1722, 3261, 1019, 3802, 4816, 1200, 681, 1595, 906],
 [1722, 706, 332, 1076, 1634, 3014, 2689, 681, 1595, 3722, 3625],
 [4014, 948, 2348, 2707, 1465],
 [22, 2273, 2036, 3192, 3304, 3982, 314, 1703, 345],
 [685, 680, 2243, 1915, 1022, 681, 1595, 906],
 [3834,
  2997,
  3959,
  4021,
  4036,
  2108,
  4036,
  3422,
  3959,
  3431,
  1377,
  1569,
  3042,
  675,
  4194],
 [4804, 4471, 4337, 3416, 3544, 4283, 3013, 681, 1595, 906],
 [3976, 4804, 1074, 1489, 3871, 2585, 2066, 4330, 4034],
 [1981, 4758, 1024, 681, 1849, 3431, 1234, 681, 1595, 906],
 [2723, 4139, 4732, 1873, 4629, 4466, 3534, 4034],
 [4471, 2278, 2075, 260, 2340, 1750, 681, 1595, 906],
 [1442, 3088],
 [1457, 4052, 1722, 1968, 2850, 3965, 981, 1307, 2745, 681, 1595, 906],
 [3431, 812, 4098, 1585, 3151, 3918, 1675, 681, 1595, 906],
 [2929, 2913, 2944, 2283, 1211, 4772, 3398, 4915, 425, 4034],
 [3183, 965, 960, 1905, 2301, 4345, 3365, 4331, 3686, 3994, 3722],
 [2723, 22, 855, 770, 3269, 557, 4994, 1923, 2497, 4034],
 [1200, 4730, 2530, 2313, 1306, 2920, 3100, 1998],
 [3181],
 [2053, 4157, 3607, 1519, 2790, 1577, 3722, 681, 1595, 906],
 [3431, 4358, 995, 861, 4780, 2306, 681, 1595, 906],
 [755, 2745, 1343, 1788, 1144],
 [3809, 2776, 1744, 779, 3331, 4362, 3191, 1546, 3961, 779, 3331, 4362, 3191],
 [2687, 3031, 2775, 3203, 2, 681, 1595, 906],
 [3590, 4411, 39, 1971, 3431, 681, 4313, 2879, 681, 1595, 906],
 [3367, 574, 4045, 960, 1971, 3431, 103, 4811, 681, 1595, 906],
 [1944, 3501, 2911, 1452, 1083, 2410, 681, 1595, 906],
 [4433, 3732, 1722, 3031, 4121, 1787, 1221],
 [4842, 3118, 2734, 1497, 2034, 3965],
 [546, 1390, 3174, 1771, 2298, 854, 4140, 3275, 906, 681, 1595, 906],
 [4333, 687, 4773, 1779, 681, 1385, 2745, 4034],
 [3431, 4111, 265, 4853, 1624, 3184, 1220, 1506, 3553, 681, 1595, 906],
 [4617, 3608, 427, 2915, 4956, 1657, 4471, 1234, 4118, 1537, 268, 4783, 4034],
 [1693, 2716, 1142, 2159, 1107, 4302, 681, 1595, 906],
 [1425, 4563, 4744, 3100, 2175, 4960, 432],
 [3986, 2301, 771, 2913, 3844, 681, 1595, 906],
 [4099, 3584, 396, 3358, 3070, 2574, 4034],
 [3804, 1414, 1200],
 [276, 3631, 685, 4465, 3376, 4715, 3850, 1225, 480],
 [2489, 180, 4737, 2280, 3506, 3471, 1020, 1497, 2142, 531, 2075],
 [3658, 3608, 2974, 640, 928, 4602, 3431, 1306],
 [1076, 1819, 167, 3382, 3589, 3164, 2652, 3431, 2989, 4034],
 [1022, 1818, 2994, 1972, 3431, 1547, 4769],
 [908, 204, 3547, 3294, 2350, 347, 4034],
 [1302,
  3389,
  3398,
  4156,
  4803,
  701,
  4439,
  1302,
  3389,
  3596,
  1265,
  2500,
  1903,
  3483],
 [2965, 3941, 609, 2489],
 [2353, 2805, 1419, 2431, 1110, 2411, 171, 681, 1595, 906],
 [569, 4411, 3549, 4043, 681, 1595, 906],
 [3671, 3777, 4632, 4180, 2477, 1065, 681, 1595, 906],
 [3216, 3063, 2842, 891, 2998, 461, 2307, 3565, 4844, 4091],
 [144, 1307, 1437, 2876, 1547, 861, 681, 1595, 906],
 [68, 3431, 803, 1729, 1200, 4946, 1221, 892, 3501, 4034],
 [4417, 1071, 1377, 1547, 4421, 3475],
 [2321, 1423, 22, 4811, 2989, 383, 2226, 3431],
 [4091, 3390, 226, 3431, 2604, 3607, 1551, 2525, 681, 1595, 906],
 [712, 3732, 343, 931, 3590, 625, 2760, 4099, 681, 1595, 906],
 [2256, 4940, 2651, 681, 1595, 906],
 [4083, 3056, 3565, 2009, 1776, 681, 1595, 906],
 [906, 1221, 231, 681, 1595, 906],
 [1722, 4362, 4175, 3465, 3651, 988, 4901, 2429, 726, 681, 1595, 906],
 [4802, 3643, 268, 269, 3525, 1442, 557, 2635],
 [4108, 48, 1818, 1381, 4946, 591, 3042, 4989],
 [4208, 2434, 4227, 281, 2767, 1221, 4157, 681, 1595, 906],
 [3431, 3491, 4271, 4415, 3847, 3547, 2644, 4640, 4034],
 [652, 2529, 2724, 333, 4229, 4261],
 [605, 3431, 1675, 1221, 4445, 3326, 1961, 681, 1595, 906],
 [23, 549, 3367, 596, 391, 201, 1965, 2641],
 [3174, 4258, 766, 4929, 4823, 681, 1595, 906],
 [4630, 1107, 4216, 908, 2690, 2484, 681, 1595, 906],
 [2676, 461, 418, 3431, 1377, 2707, 1871],
 [3501, 4068, 1951, 2374, 3861, 3086, 1212, 4642, 681, 1595, 906],
 [2948, 1122, 3431, 1997, 2435, 3422, 681, 1595, 906],
 [1971, 3431, 3607, 3100, 1675, 960],
 [4413, 3465, 3597, 154, 2273, 2892, 396, 4808, 681, 1595, 906],
 [4526, 3042, 196, 3216, 1961, 3455, 4654],
 [557, 2856, 3832, 1209, 1771, 681, 1595, 906],
 [3431, 4016, 2171, 2530, 2710, 3174, 681, 1595, 906],
 [1798, 1016, 1340, 2633, 1167, 2676, 4988, 2637],
 [4093, 4946, 1144],
 [892, 481, 2769, 1792, 516, 3393, 4093, 681, 1595, 906],
 [958, 444, 4085, 3472, 1537, 3607, 2802, 2709, 687, 1576, 356, 4034],
 [1971, 3431, 163, 1116, 3936, 1894, 4064, 1253, 3388, 4761, 681, 1595, 906],
 [1519, 4068, 3975, 1506, 3624, 681, 1595, 906],
 [3492, 1333, 157, 965, 1122, 1099, 681, 1595, 906],
 [1971,
  3431,
  3115,
  4362,
  4232,
  2489,
  4339,
  4828,
  1557,
  268,
  1378,
  855,
  2460,
  681,
  1595,
  906],
 [2821, 2659, 3431, 16, 3080, 3066, 681, 1595, 906],
 [4654, 1298, 1034, 960, 4403, 2097],
 [3431, 180, 1396],
 [908, 1313, 4651, 3547, 2313, 3986, 4034],
 [1657,
  2066,
  2492,
  4718,
  1773,
  1667,
  4588,
  3431,
  2794,
  2066,
  1444,
  2185,
  1442],
 [1686, 1055, 364, 1189, 1658, 779, 1518],
 [144, 3036, 3029, 3268, 257, 3216],
 [3752, 3875, 190, 2476, 2045],
 [2910, 812, 938, 1424, 4273, 2892, 3658, 1059, 4667, 1843, 681, 1595, 906],
 [4750, 2489, 4339, 4466, 4034],
 [4424, 771, 2856, 3747, 468, 116, 432, 2533, 4142],
 [2116, 2790, 3597, 4331, 1178, 1742, 2912, 3724],
 [3149, 2913, 4989, 1689],
 [191, 2125, 3185, 4595, 1733, 2249, 4988, 4020],
 [2960, 1242, 392, 3031],
 [2295, 22, 1787, 180, 198, 3459, 2644, 3056],
 [2285],
 [4707, 418, 3063, 906, 2891, 1489, 681, 1595, 906],
 [3431, 3037, 1371, 3019, 516, 4403],
 [1875, 751, 2493, 701, 3527, 681, 1595, 906],
 [465, 4403, 327, 378, 192, 597, 3431, 4152],
 [431, 4563, 4744, 1571, 2435, 3431, 1574],
 [2850, 4772, 4677, 3933, 3459, 3431, 2840, 4034],
 [626, 22, 719, 1779, 1280, 1625, 2061, 1675, 681, 1595, 906],
 [3, 3088, 260],
 [137, 1754, 402, 1377, 4769, 681, 1595, 906],
 [2033, 723, 1694, 1743, 3626, 4283, 2393, 4074, 636, 4034],
 [1577, 3612, 1658, 1326, 1379, 2923, 1184, 2716, 681, 1595, 906],
 [1787, 2489, 4828, 2574, 3782, 2531, 4989],
 [1647, 1905, 3070, 2281, 859, 2920, 619, 2760, 4439, 1618, 557],
 [2489, 79, 1497, 1446, 1659],
 [4059, 1689, 3431, 2455, 2475, 3610, 2721, 681, 1595, 906],
 [854, 4413, 2360, 479, 2147, 1508, 681, 1595, 906],
 [3986, 511, 3188, 3408, 2642, 854],
 [2689, 2295, 3066, 1967, 3182, 1849, 2324, 681, 1595, 906],
 [2681, 2665, 1967, 636, 3631, 2806, 2806],
 [781, 1376, 3759, 2342, 4324, 1377, 681, 1595, 906],
 [1468, 4365, 4266, 2435, 1468, 1637, 2183, 749],
 [1742, 79, 4053, 4929, 1522, 905, 424, 2460, 2298, 1508],
 [1497, 476, 1592, 706, 4794, 4497, 4034],
 [174, 4504, 899, 4339, 3063, 1214, 2745, 2530, 681, 1595, 906],
 [1037, 4142, 3755, 1017, 2301, 3879],
 [148, 4424, 4504, 3086, 782, 751, 3994, 1937, 760, 4142, 4034],
 [1574, 4834, 1347, 4146, 2281, 576, 2511, 1340],
 [3100, 3325, 4403, 1871, 4680],
 [3431, 4134, 2337, 4632, 1306, 2719, 1787, 1506, 1171, 681, 1595, 906],
 [1343, 4031, 145, 3431, 517, 4026, 3100, 4680, 4034],
 [1743, 2736, 960, 3431],
 [540, 1363, 4946, 3501, 1996, 1420, 3382],
 [821, 65, 4429, 1668, 3016, 1789, 4523, 1378, 3174],
 [4417, 4403, 625, 1221, 3431, 1716],
 [1787, 2927, 1971, 3431, 1110, 1682, 4977, 263, 23, 4482, 681, 1595, 906],
 [557, 830, 760, 3847, 4102, 2824, 1043, 4366, 4034, 3332, 681, 1595, 906],
 [1953, 3206, 1901, 4466, 4466, 4466, 681, 1595, 906],
 [134, 717, 2533, 3363, 3847, 4804, 3146, 2024],
 [2489, 2131, 3982, 168, 2489, 3624, 1565, 2725, 27],
 [1617, 3455, 4605, 1184, 3527, 681, 1595, 906],
 [3367, 2429, 3315, 2036, 1722, 1295, 488, 1736, 681, 1595, 906],
 [3431,
  3408,
  4246,
  3477,
  1722,
  1806,
  3215,
  3389,
  3043,
  3301,
  1881,
  4998,
  4034],
 [1522, 11, 3425, 2497, 1141, 1063],
 [461, 1900, 2081, 3097, 4744, 2489, 383, 3459],
 [2078, 4808, 3786, 4142, 2967, 681, 1595, 906],
 [4947, 3816, 476, 4439, 3365, 1101, 3431, 167, 4034],
 [2748, 2639, 4772, 4602, 4682, 803, 3007, 3431, 681, 1595, 906],
 [3349, 1947, 1377, 3167, 118, 681, 1595, 906],
 [476, 3144, 4339, 1659, 1897, 3941, 4257, 3144, 681, 1595, 906],
 [1467, 3053, 1722, 2108, 428, 2290, 4016, 3425, 2827, 23, 632, 4998],
 [2725, 103, 1241, 4961, 3321, 4659, 3124, 681, 1595, 906],
 [4403, 1445, 4413, 4842, 4869, 4632],
 [760, 3070, 290, 4242, 4732, 627],
 [69,
  1062,
  681,
  1595,
  906,
  1306,
  1242,
  2066,
  2582,
  2879,
  4715,
  4674,
  2511,
  681,
  1595,
  906],
 [2880, 4378, 2616, 1571, 4339, 3883, 1971, 3431, 4152, 4034],
 [2839, 4622, 1787, 2609, 3321, 831, 4823, 304, 1328, 4403, 4034],
 [4512, 1425, 3562, 465, 681, 1595, 906],
 [3446, 4617, 2755, 3857, 476, 3007, 65],
 [2301,
  4753,
  2097,
  4428,
  2071,
  366,
  1260,
  1855,
  1326,
  276,
  915,
  4340,
  3146,
  1340],
 [4403, 512, 154, 4769, 3001, 4780, 4413, 1371, 681, 1595, 906],
 [418, 198, 4671, 1455, 3431, 3063, 1298, 1022, 2348, 4324, 4034],
 [1389, 3014, 749, 854, 1221, 2930, 1686, 4034],
 [712, 693, 3336, 3747, 3514, 4152, 1625, 1517],

###**Embedding Representation**

In [25]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  948 4093 3483]
 [   0    0    0 ...  760 2216 4034]
 [   0    0    0 ... 1624 1547 4439]
 ...
 [   0    0    0 ...  681 1595  906]
 [   0    0    0 ... 1490 3641 2359]
 [   0    0    0 ... 3184 4295 3273]]

In [26]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3031,
        167, 3408, 2295, 1099,  476, 3144,  948, 4093, 3483], dtype=int32)

In [27]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [28]:
len(embedded_docs),y.shape

(18283, (18283,))

In [29]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [30]:
X_final.shape,y_final.shape

((18283, 20), (18283,))

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

###**Model Training**

In [32]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - accuracy: 0.7804 - loss: 0.4244 - val_accuracy: 0.9042 - val_loss: 0.2154
Epoch 2/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 5s 26ms/step - accuracy: 0.9395 - loss: 0.1499 - val_accuracy: 0.9160 - val_loss: 0.1978
Epoch 3/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - accuracy: 0.9585 - loss: 0.1054 - val_accuracy: 0.9158 - val_loss: 0.2390
Epoch 4/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - accuracy: 0.9731 - loss: 0.0733 - val_accuracy: 0.9133 - val_loss: 0.2266
Epoch 5/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 11s 39ms/step - accuracy: 0.9797 - loss: 0.0658 - val_accuracy: 0.8951 - val_loss: 0.2905
Epoch 6/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 8s 26ms/step - accuracy: 0.9850 - loss: 0.0511 - val_accuracy: 0.9062 - val_loss: 0.3051
Epoch 7/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 7s 34ms/step - accuracy: 0.9884 - loss: 0.0361 - val_accuracy: 0.9090 - val_loss: 0.3823
Epoch 8/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 10s 34ms/step - accuracy: 0.9913 - loss: 0.0308 - val_accuracy: 0.9088 - val_loss: 0.3365
Epoch 9/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 6s 29ms/step - accuracy: 0.9942 - loss: 0.0241 - val_accuracy: 0.9080 - val_loss: 0.4580
Epoch 10/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - accuracy: 0.9973 - loss: 0.0133 - val_accuracy: 0.9040 - val_loss: 0.5117

###**Adding Dropout**

In [33]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

###**Performance Metrics And Accuracy**

In [34]:
y_pred = model.predict(X_test)

189/189 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

In [35]:
# Use the predict method to get the probability outputs
y_pred_prob = model.predict(X_test)

189/189 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

In [36]:
# Convert the probabilities to class labels using a threshold (0.5 for sigmoid)
y_pred = (y_pred_prob > 0.5).astype(int)

In [37]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred)

array([[2389, 1026],
       [ 904, 1715]])

In [38]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.6801458402386477

In [39]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.73      0.70      0.71      3415
           1       0.63      0.65      0.64      2619

    accuracy                           0.68      6034
   macro avg       0.68      0.68      0.68      6034
weighted avg       0.68      0.68      0.68      6034

**Note:**

**Though the dataset is corrupted, that's why I am having bad prediction**